docker rmi "lab4_register-service" 
docker rmi "lab4_login-service" 
docker rmi "lab4_status-service" 
docker rmi "lab4_list-service" 
docker rmi "lab4_add-service" 
docker rmi "lab4_remove-service" 
docker rmi "mysql:8.0" 