version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  login-service:
    build:
      context: ./user_services/login  
    container_name: login-container
    depends_on:
      - mysql-db
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db

  register-service:
    build:
      context: ./user_services/register  
    container_name: register-container
    depends_on:
      - mysql-db
    ports:
      - "5001:5001"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db

  add-service:
    build:
      context: ./product_services/add  
    container_name: add-container
    depends_on:
      - mysql-db
    ports:
      - "5002:5002"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db

  list-service:
    build:
      context: ./product_services/list 
    container_name: list-container
    depends_on:
      - mysql-db
    ports:
      - "5003:5003"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db

  remove-service:
    build:
      context: ./product_services/remove  
    container_name: remove-container
    depends_on:
      - mysql-db
    ports:
      - "5004:5004"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db
  
  status-service:
    build:
      context: ./order_services/status  
    container_name: status-container
    depends_on:
      - mysql-db
    ports:
      - "5005:5005"
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app_db
      
volumes:
  db_data:
