apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-microservice
  labels:
    app: add-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-microservice
  template:
    metadata:
      labels:
        app: add-microservice
    spec:
      containers:
      - name: add-microservice-container
        image: lab4_add-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "app_db"
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: add-microservice-service
spec:
  type: NodePort
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30003
  selector:
    app: login-microservice
