apiVersion: apps/v1
kind: Deployment
metadata:
  name: list-microservice
  labels:
    app: list-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: list-microservice
  template:
    metadata:
      labels:
        app: list-microservice
    spec:
      containers:
      - name: list-microservice-container
        image: lab4_list-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "app_db"
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: list-microservice-service
spec:
  type: NodePort
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 30004
  selector:
    app: list-microservice
