apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-microservice
  labels:
    app: login-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-microservice
  template:
    metadata:
      labels:
        app: login-microservice
    spec:
      containers:
      - name: login-microservice-container
        image: lab4_login-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "app_db"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: login-microservice-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001  
  selector:
    app: login-microservice
