apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-microservice
  labels:
    app: register-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-microservice
  template:
    metadata:
      labels:
        app: register-microservice
    spec:
      containers:
      - name: register-microservice-container
        image: lab4_register-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "app_db"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: register-microservice-service
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30002 
  selector:
    app: register-microservice
