apiVersion: apps/v1
kind: Deployment
metadata:
  name: remove-microservice
  labels:
    app: remove-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remove-microservice
  template:
    metadata:
      labels:
        app: remove-microservice
    spec:
      containers:
      - name: remove-microservice-container
        image: lab4_remove-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "app_db"
        ports:
        - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: remove-microservice-service
spec:
  type: NodePort
  ports:
  - port: 5004
    targetPort: 5004
    nodePort: 30005
  selector:
    app: remove-microservice
