apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-microservice
  labels:
    app: status-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status-microservice
  template:
    metadata:
      labels:
        app: status-microservice
    spec:
      containers:
      - name: status-microservice-container
        image: lab4_status-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "app_db"
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: status-microservice-service
spec:
  type: NodePort
  ports:
  - port: 5005
    targetPort: 5005
    nodePort: 30006
  selector:
    app: status-microservice
